# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
acts = Act.create([
  { name: ' 24-7 Spyz'},
{ name: ' Ad Frank'},
{ name: ' Al Kooper'},
{ name: ' Aimee Mann'},
{ name: ' Babe The Blue Ox'},
{ name: ' Barenaked Ladies'},
{ name: ' Ben Vaughn'},
{ name: ' Bill Janovitz'},
{ name: ' Blake Babies'},
{ name: ' Blind Robbins'},
{ name: ' Blockhouses'},
{ name: ' Botswanas'},
{ name: ' Brainiac'},
{ name: ' Cameraface'},
{ name: ' Candy Butchers'},
{ name: ' Cavedogs'},
{ name: ' Cheap Trick'},
{ name: ' Chopper'},
{ name: ' Corin Ashley'},
{ name: ' Coward'},
{ name: ' Creme Brulee'},
{ name: ' DDT'},
{ name: ' Delta Clutch'},
{ name: ' Dirt Merchants'},
{ name: ' District 13'},
{ name: ' Dum Dum Boys'},
{ name: ' Eve\'s Plum'},
{ name: ' Five Eight'},
{ name: ' Future Islands'},
{ name: ' Gang of Four'},
{ name: ' Ghosts'},
{ name: ' Ghostshirts'},
{ name: ' Gigolo Aunts'},
{ name: ' Green'},
{ name: ' Guided by Voices'},
{ name: ' Headzup'},
{ name: ' Heavy Stud'},
{ name: ' Heidi'},
{ name: ' Helium'},
{ name: ' Hugh Cornwell (Stranglers)'},
{ name: ' Imperial Teen'},
{ name: ' Jawbox'},
{ name: ' Jen Trynin'},
{ name: ' Jokerz Wild'},
{ name: ' Jon Brion'},
{ name: ' Jules Verdone'},
{ name: ' Juliana Hatfield 3'},
{ name: ' Letters to Cleo'},
{ name: ' Little John'},
{ name: ' Los Euclids'},
{ name: ' Lotion'},
{ name: ' Love'},
{ name: ' Loved Ones'},
{ name: ' Marah'},
{ name: ' Massengirls'},
{ name: ' McNiknix'},
{ name: ' Mean Creek'},
{ name: ' Miracle Legion'},
{ name: ' Mistle Thrush'},
{ name: ' Morhpine'},
{ name: ' Nada Surf'},
{ name: ' Pat Luciano'},
{ name: ' Poundcake'},
{ name: ' Quickfix'},
{ name: ' Raging Teens'},
{ name: ' Scott Janovitz'},
{ name: ' Sheila Divine'},
{ name: ' Silverchair'},
{ name: ' Skip The Gutter'},
{ name: ' Sloan'},
{ name: ' Small Factory'},
{ name: ' Superdrag'},
{ name: ' Talking To Animals'},
{ name: ' Tanya Donelly'},
{ name: ' Thalia Zedeck'},
{ name: ' The Barnies'},
{ name: ' The Charms'},
{ name: ' The Figgs'},
{ name: ' The Friggs'},
{ name: ' The Furors'},
{ name: ' The Gravy'},
{ name: ' The Outlets'},
{ name: ' The Pants'},
{ name: ' The Pills'},
{ name: ' The Posies'},
{ name: ' The Rapid Shave'},
{ name: ' The Red Telephone'},
{ name: ' The Reducers'},
{ name: ' The Sheila Divine'},
{ name: ' The Shods'},
{ name: ' The Streams'},
{ name: ' The Texas Governor'},
{ name: ' The Throbbers'},
{ name: ' The Upper Crust'},
{ name: ' They Might Be Giants'},
{ name: ' Those Melvins'},
{ name: ' Tinderbox'},
{ name: ' Tracy Bonham'},
{ name: ' Tuff n Pasty'},
{ name: ' Tuscadero'},
{ name: ' Velocity Girl'},
{ name: ' Verbena'},
{ name: ' Versus'},
{ name: ' Wheat'},
{ name: ' Will Dailey'},
{ name: ' Yawnmower'},
{ name: ' Young Men Carbuncular'},
{ name: ' 100 Faces'}
  ])