# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
songs = Song.create([
{ title: 'Get Rough', release_id: 2, tracknumber: 6},
{ title: 'The Ballad of the Gravel Pit', release_id: 2, tracknumber: 2},
{ title: 'Unit Three', release_id: 2, tracknumber: 3},
{ title: 'Baby Gap', release_id: 2, tracknumber: 4},
{ title: 'Best Friend', release_id: 2, tracknumber: 5},
{ title: 'Enemy', release_id: 2, tracknumber: 7},
{ title: 'Why', release_id: 2, tracknumber: 8},
{ title: 'Star Treatment', release_id: 2, tracknumber: 9},
{ title: 'Curious', release_id: 2, tracknumber: 10},
{ title: 'Race Car', release_id: 2, tracknumber: 11},
{ title: 'Short Western Film', release_id: 2, tracknumber: 12},
{ title: 'New Haven', release_id: 4, tracknumber: 1},
{ title: 'Thought Powered Cloud', release_id: 4, tracknumber: 2},
{ title: 'Something\'s Growing Inside', release_id: 4, tracknumber: 3},
{ title: 'The Shivers', release_id: 4, tracknumber: 4},
{ title: 'Officer Dwight Boyd', release_id: 4, tracknumber: 5},
{ title: 'Time To Leave The Cradle', release_id: 4, tracknumber: 6},
{ title: 'Favorite Scar', release_id: 4, tracknumber: 7},
{ title: 'Skipping Throught The Chill', release_id: 4, tracknumber: 8},
{ title: 'Teenage Witch', release_id: 4, tracknumber: 9},
{ title: 'King Of Everything', release_id: 4, tracknumber: 10},
{ title: 'Drink You Up', release_id: 4, tracknumber: 11},
{ title: 'The Prayer', release_id: 4, tracknumber: 12},
{ title: 'The Judas Lament', release_id: 4, tracknumber: 13},
{ title: 'I Climb (Up His Tree)', release_id: 3, tracknumber: 1},
{ title: 'Bolt Of Light', release_id: 3, tracknumber: 2},
{ title: 'The Mosquito', release_id: 3, tracknumber: 3},
{ title: 'Where The Flying Things Go', release_id: 3, tracknumber: 4},
{ title: 'Stumbling Sideways', release_id: 3, tracknumber: 5},
{ title: 'Favorite', release_id: 3, tracknumber: 6},
{ title: 'Free To Be Me And Thee', release_id: 3, tracknumber: 7},
{ title: 'When Will Our Bucket Come Up Dry', release_id: 3, tracknumber: 8},
{ title: 'Millions Of Miles', release_id: 3, tracknumber: 9},
{ title: 'The Ballad Of Ezra Messenger', release_id: 3, tracknumber: 10},
{ title: 'The Rise Of Abimelech DuMont', release_id: 3, tracknumber: 11},
{ title: 'The Marchers Wander In', release_id: 3, tracknumber: 12},
{ title: 'Get Tangled!', release_id: 3, tracknumber: 13},
{ title: 'Standing In My Way', release_id: 5, tracknumber: 1},
{ title: 'Burn', release_id: 5, tracknumber: 2},
{ title: 'You\'re A Lie', release_id: 5, tracknumber: 3},
{ title: 'She\'s Right Yeah, Yeah, Yeah, Yeah', release_id: 5, tracknumber: 4},
{ title: 'Free Enterprise', release_id: 5, tracknumber: 5},
{ title: 'I Want You', release_id: 5, tracknumber: 6},
{ title: 'Sing A Long', release_id: 5, tracknumber: 7},
{ title: 'Ready For Many', release_id: 5, tracknumber: 8},
{ title: 'Fainting', release_id: 5, tracknumber: 9},
{ title: 'This Old Clock Doesn\'t Make Any Sense', release_id: 5, tracknumber: 10},
{ title: 'Tyrannosaurus', release_id: 5, tracknumber: 11},
{ title: 'Focusing On One Thing And Achieving It', release_id: 7, tracknumber: 1},
{ title: 'The Southern Crawl', release_id: 7, tracknumber: 2},
{ title: 'She\'s Right Yeah Yeah Yeah Yeah', release_id: 7, tracknumber: 3},
{ title: 'I Want You', release_id: 7, tracknumber: 4},
{ title: 'The Dark Cloud Dance', release_id: 7, tracknumber: 5},
{ title: '116th Dream', release_id: 7, tracknumber: 6},
{ title: 'The Devil', release_id: 7, tracknumber: 7},
{ title: 'Paul Westerberg', release_id: 7, tracknumber: 8},
{ title: 'The Slow Song', release_id: 7, tracknumber: 9},
{ title: 'King Kong', release_id: 7, tracknumber: 10},
{ title: 'Best Is Yet To Be', release_id: 7, tracknumber: 11},
{ title: 'Suburban Rock', release_id: 7, tracknumber: 12},
{ title: 'Teenage Lust', release_id: 7, tracknumber: 13},
{ title: 'Baby, Yeah', release_id: 7, tracknumber: 14},
{ title: '(Suckin\' On A) Holiday Treat', release_id: 7, tracknumber: 15},
{ title: 'The Simple Fact', release_id: 7, tracknumber: 16},
{ title: 'Hell', release_id: 7, tracknumber: 17},
{ title: 'Angels We Have Heard On High', release_id: 7, tracknumber: 18},
{ title: 'Hit The Sack', release_id: 7, tracknumber: 19},
{ title: 'The Purple Priest', release_id: 7, tracknumber: 20},
{ title: 'Queen Of Motion', release_id: 7, tracknumber: 21},
{ title: 'High \'n\' Dry (Saturday Night)', release_id: 7, tracknumber: 22},
{ title: 'Wicked Witch', release_id: 6, tracknumber: 3},
{ title: 'Rusty Purple Pin', release_id: 6, tracknumber: 4},
])